readd cypress

diff --git a/githooks/pre-push b/githooks/pre-push
--- a/githooks/pre-push
+++ b/githooks/pre-push
@@ -12,3 +12,11 @@ else
     echo "Failed to deploy check the logs"
     exit 1
 fi
+
+
+if yarn cypress:run ; then
+    echo "Sucessfully ran browser tests"
+else
+    echo "Failed browser tests check the logs"
+    exit 1
+fi
