split up files to have browser one and node (#20)
* split up files to have browser one and node

* test runing examples before and after

* rename build:node

* fix spacing

* remove examples before installing

* throw error

* fix typo

* throw error?

* undo changes

* instructions to contribute

* try to use workfows

* test different thing

* typo 2

* throw error one more time

* test 3

* remove extra examples run

* fix lint issues and add it to build

* debug deploy

* added engines

* change version of image

* update version

* lower version of yarn

* specify build number

diff --git a/githooks/pre-push b/githooks/pre-push
--- a/githooks/pre-push
+++ b/githooks/pre-push
@@ -1,12 +1,21 @@
 #!/bin/bash
-if npm run lint; then
+if yarn lint; then
     echo "Sucessfully passed linter"
 else
     echo "Failed linter"
+    exit 1
 fi
 
-if npm run deploy ; then
+if yarn deploy ; then
     echo "Sucessfully deployed"
 else
     echo "Failed to deploy check the logs"
+    exit 1
+fi
+
+if yarn documentationjs ; then
+    echo "Sucessfully deployed"
+else
+    echo "Failed to deploy check the logs"
+    exit 1
 fi
