test different thing

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,6 +28,14 @@ jobs:
           key: v1-dependencies-{{ checksum "package.json" }}
 
       - run: yarn deploy
+      - run: |
+            set -eo pipefail
+            if yarn yarn examples ; then
+              echo "Sucessfully ran examples"
+            else
+                echo "Failed to on examples"
+                exit 1
+            fi
   test:
     docker:
       # specify the version you desire here
